image: node:15.14.0
pipelines:
  pull-requests:
    '**':
      - parallel:
        - step:
            name: Test & Lint & Build
            caches:
              - node
              - npm
            script:
              - npm ci --prefer-offline --no-audit --cache .npm
              - npx eslint .
              - npm test
              - npm run build
definitions:
  caches:
    npm: .npm
